#!/usr/bin/env python3
"""
Pitch detection server for Nirmaan YouTube Dashboard.
Serves the dashboard + provides /api/scan endpoint that downloads
transcripts via yt-dlp and detects Super Pass pitch keywords.

Usage: python3 pitch_server.py
Runs on port 8766
"""

import http.server
import json
import os
import re
import subprocess
import tempfile
import threading
import urllib.parse
from pathlib import Path

SERVE_DIR = Path(__file__).parent
PORT = 8766

# ── Pitch keyword patterns ────────────────────────────────────────────────────
PITCH_PATTERNS = {
    "pass999": [
        r"999",
        r"સુપર\s*પાસ",       # Gujarati "Super Pass"
        r"superpass",
        r"super\s*pass",
        r"સુપરપાસ",
        r"નિર્માણ\s*સુપર",   # "Nirmaan Super"
        r"nirmaan\s*super",
        r"nirmaan\s*pass",
        r"nirman\s*pass",
        r"6\s*મહિના",        # 6 month validity (Super Pass feature)
        r"six\s*month",
    ],
    "trial": [
        r"ટ્રાયલ",
        r"trial",
        r"ફ્રી\s*ટ્રાયલ",
        r"free\s*trial",
        r"FREE\s*TRIAL",
        r"1\s*રૂ",
        r"₹\s*1\b",
        r"rs\.?\s*1\b",
        r"1\s*rupee",
        r"2\s*દિવસ",         # 2 days trial
        r"2\s*days",
        r"ઉપલબ્ધ\s*છે",      # "available hai" — used in trial CTAs
    ],
    "pass499": [
        r"499",
    ],
}

def compile_patterns():
    return {
        ptype: [re.compile(p, re.IGNORECASE) for p in patterns]
        for ptype, patterns in PITCH_PATTERNS.items()
    }

COMPILED = compile_patterns()

# ── Transcript download & analysis ───────────────────────────────────────────

def clean_vtt(vtt_text):
    """Strip VTT timing tags and deduplicate lines."""
    lines = vtt_text.splitlines()
    cleaned = []
    seen = set()
    for line in lines:
        if line.startswith("WEBVTT") or line.startswith("NOTE") or "-->" in line or not line.strip():
            continue
        # Remove inline timing tags like <00:00:00.000><c>...</c>
        plain = re.sub(r"<[^>]+>", "", line).strip()
        if plain and plain not in seen:
            seen.add(plain)
            cleaned.append(plain)
    return " ".join(cleaned)


def detect_pitches(transcript_text):
    """Return list of detected pitch types from transcript text."""
    found = []
    for ptype, patterns in COMPILED.items():
        for pat in patterns:
            if pat.search(transcript_text):
                found.append(ptype)
                break  # one match per type is enough
    return found


def scan_video(video_id):
    """Download YouTube auto-generated captions for video_id and detect pitch keywords.

    YouTube generates auto-captions (in proper Gujarati script) for live stream
    replays within 24-48 hours of upload. This is the most reliable source —
    accurate Gujarati text, fast download (~10s per video).

    If captions are not yet available (video uploaded < 48h ago), returns
    pending=True so the dashboard can show a ⏳ indicator and retry later.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        vtt_path = os.path.join(tmpdir, f"{video_id}.gu.vtt")
        try:
            subprocess.run(
                [
                    "yt-dlp",
                    "--write-auto-subs",
                    "--skip-download",
                    "--sub-langs", "gu",
                    "-o", os.path.join(tmpdir, "%(id)s.%(ext)s"),
                    f"https://www.youtube.com/watch?v={video_id}",
                ],
                capture_output=True, text=True, timeout=60,
            )

            if not os.path.exists(vtt_path):
                # Captions not yet generated by YouTube (video too recent)
                return {"videoId": video_id, "types": [], "pending": True,
                        "error": "captions not available yet — retry in 24-48h"}

            with open(vtt_path, "r", encoding="utf-8") as f:
                raw_vtt = f.read()

            transcript = clean_vtt(raw_vtt)
            types = detect_pitches(transcript)
            return {"videoId": video_id, "types": types, "pending": False,
                    "source": "transcript", "error": None}

        except subprocess.TimeoutExpired:
            return {"videoId": video_id, "types": [], "pending": False, "error": "timeout"}
        except Exception as e:
            return {"videoId": video_id, "types": [], "pending": False, "error": str(e)}


# ── HTTP Server ───────────────────────────────────────────────────────────────

class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(SERVE_DIR), **kwargs)

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)

        if parsed.path == "/api/scan":
            self._handle_scan(parsed.query)
        else:
            super().do_GET()

    def _handle_scan(self, query_string):
        params = urllib.parse.parse_qs(query_string)
        ids_raw = params.get("ids", [""])[0]
        if not ids_raw:
            self._json_response({"error": "missing ids parameter"}, 400)
            return

        # Sanitize video IDs (YouTube IDs are alphanumeric + - _)
        video_ids = [
            vid.strip() for vid in ids_raw.split(",")
            if re.match(r"^[A-Za-z0-9_\-]{5,20}$", vid.strip())
        ]

        if not video_ids:
            self._json_response({"error": "no valid video IDs"}, 400)
            return

        results = []
        for vid in video_ids:
            result = scan_video(vid)
            results.append(result)

        self._json_response({"results": results})

    def _json_response(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        # Only log API calls, suppress static file noise
        if "/api/" in args[0] if args else False:
            super().log_message(fmt, *args)


if __name__ == "__main__":
    os.chdir(SERVE_DIR)
    server = http.server.HTTPServer(("", PORT), Handler)
    print(f"✅ Nirmaan Dashboard running at http://localhost:{PORT}/nirmaan-youtube-dashboard.html")
    print(f"   Pitch scan API: http://localhost:{PORT}/api/scan?ids=VIDEO_ID1,VIDEO_ID2")
    print(f"   Press Ctrl+C to stop.\n")
    server.serve_forever()
